- type: job
  id: ShaftMiner
  name: job-name-miner
  description: job-description-miner
  playTimeTracker: JobMiner
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: ShaftMinerGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: ShaftMinerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
